update 1.15.0
AnacondaRecipes/onnxruntime-feedstock pull request #3
Opened 2023-06-16 21:19 UTC by Arishamays1

2023-06-16 21:20 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_cahjjlszws/clone/recipe/meta.yaml:24: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_cahjjlszws/clone/recipe/meta.yaml:33: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cahjjlszws/clone/recipe/meta.yaml:34: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cahjjlszws/clone/recipe/meta.yaml:35: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cahjjlszws/clone/recipe/meta.yaml:37: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cahjjlszws/clone/recipe/meta.yaml:38: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_cahjjlszws/clone/recipe/meta.yaml:47: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:59: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-24 09:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_a3vcr_cr49/clone/recipe/meta.yaml:24: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_a3vcr_cr49/clone/recipe/meta.yaml:33: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a3vcr_cr49/clone/recipe/meta.yaml:34: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a3vcr_cr49/clone/recipe/meta.yaml:35: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a3vcr_cr49/clone/recipe/meta.yaml:37: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a3vcr_cr49/clone/recipe/meta.yaml:38: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_a3vcr_cr49/clone/recipe/meta.yaml:47: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:59: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-24 09:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_48jluuu_1j/clone/recipe/meta.yaml:24: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_48jluuu_1j/clone/recipe/meta.yaml:34: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_48jluuu_1j/clone/recipe/meta.yaml:35: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_48jluuu_1j/clone/recipe/meta.yaml:36: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_48jluuu_1j/clone/recipe/meta.yaml:38: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_48jluuu_1j/clone/recipe/meta.yaml:39: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_48jluuu_1j/clone/recipe/meta.yaml:48: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:77: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-27 20:03 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_26a3jcc79e/clone/recipe/meta.yaml:25: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_26a3jcc79e/clone/recipe/meta.yaml:35: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_26a3jcc79e/clone/recipe/meta.yaml:36: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_26a3jcc79e/clone/recipe/meta.yaml:37: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_26a3jcc79e/clone/recipe/meta.yaml:39: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_26a3jcc79e/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_26a3jcc79e/clone/recipe/meta.yaml:49: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:65: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-27 20:45 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:31: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:36: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:43: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:46: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_9bpb03leln/clone/recipe/meta.yaml:55: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:65: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-28 00:06 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:31: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_638a2a9sv7/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-28 00:09 UTC, sumit0190 commented
@Arishamays1 I took a look at the logs and made some changes that will hopefully get the build working:
- We can't build the package tests with our current setup. I faced this problem the last time too but unfortunately I couldn't find the time to locate and fix the problem. So the tests have been disabled and removed.
- You need to call the `build` script with the `allow_running_as_root` option, as our CI workers do have root privileges. This is fine, and has no effect on the rest of the build process.
- You need to remove `libprotobuf` from the build environment, as that (and other `protobuf` related dependencies) are vendored in at the moment.
- I haven't looked at the patches yet, so I am not sure if you need those.

2023-06-28 03:03 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_a62nwh2k8f/clone/recipe/meta.yaml:31: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_a62nwh2k8f/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a62nwh2k8f/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a62nwh2k8f/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a62nwh2k8f/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a62nwh2k8f/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_a62nwh2k8f/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-28 04:14 UTC, sumit0190 commented on recipe/bld.bat
> +    --allow_running_as_root ^
You need to remove this option from `bld.bat`; it's for Unix only.

2023-06-28 16:43 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_dflfyz09el/clone/recipe/meta.yaml:31: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_dflfyz09el/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_dflfyz09el/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_dflfyz09el/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_dflfyz09el/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_dflfyz09el/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_dflfyz09el/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-28 20:15 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:31: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_3975qbzphl/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-28 23:28 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:31: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_a8_okz6c6l/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-28 23:28 UTC, sumit0190 commented
Seems like `ninja` was misbehaving a bit on `win-64`, so I removed it; hopefully `win-64` is able to build fully now (it did build correctly the last time, but the incorrect `makefile` behavior was causing `setup.py` to fail). Make sure to adjust the `meta.yaml` accordingly.

2023-06-29 01:02 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_b3v48lc4kn/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-06-30 18:37 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_4co7mxpdoy/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-05 18:10 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_da7ddsohg2/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-05 18:31 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_1294uxukty/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-05 18:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_cb838tgdz1/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-10 18:56 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
Traceback (most recent call last):
  File "/opt/conda/envs/linter/bin/conda-lint", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/run.py", line 107, in main
    result = linter.lint(
             ^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/lint/__init__.py", line 620, in lint
    msgs = self.lint_file(
           ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/lint/__init__.py", line 684, in lint_file
    recipe = _recipe.Recipe.from_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/recipe.py", line 340, in from_file
    raise exc
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/recipe.py", line 331, in from_file
    recipe.load_from_string(text.read())
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/recipe.py", line 214, in load_from_string
    self.render()
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/anaconda_linter/recipe.py", line 421, in render
    self.meta = yaml.load(yaml_text)
                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 141, in compose_node
    node = self.compose_sequence_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 185, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/linter/lib/python3.11/site-packages/ruamel/yaml/composer.py", line 117, in compose_node
    raise ComposerError(
ruamel.yaml.composer.ComposerError: found undefined alias '*/api-ms-win-core-path-l1-1-0.dll'
  in "<unicode string>", line 26, column 7:
        - **/api-ms-win-core-path-l1-1-0.dll
          ^ (line: 26)

ERROR conda.cli.main_run:execute(47): `conda run conda-lint /tmp/abs_f8f6273tqa/clone` failed. (See above for error)
</details>

2023-07-10 20:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_ebrus3f4_x/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-11 17:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:33: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:36: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:43: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:46: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_a2e_e86owg/clone/recipe/meta.yaml:55: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-11 17:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_3axyy0_4le/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-12 11:52 UTC, sumit0190 commented on recipe/meta.yaml
> +    - numpy 1.21.5   # [py<310]
Why are these in the `build` section AND the `host` section? Just putting them in `host` should be sufficient.

2023-07-12 11:53 UTC, sumit0190 commented on recipe/meta.yaml
> +    - numpy 1.21.5 # [py<310]
Where is this version number (1.21.5) coming from? I don't see it in the upstream requirements, maybe this is not needed?

2023-07-12 11:58 UTC, sumit0190 approved these changes
LGTM apart from minor `numpy` related comments.

2023-07-12 12:22 UTC, skupr-anaconda commented on recipe/bld.bat
> +%python% tools/ci_build/build.py ^
```suggestion
%PYTHON% tools/ci_build/build.py ^
```
Just a convention and for visibility

2023-07-12 12:22 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    #   Workaround for https://github.com/microsoft/onnxruntime/issues/13225
Could you place a comment above the corresponding patch to avoid confusing?

2023-07-12 12:22 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - numpy # [py>=310]
Should it be like:
`- numpy {{ numpy }}  # [py>=310]` so, in runtime, a correct version will be picked up

2023-07-12 12:22 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  skip: True # [py>310 or ppc64le or s390x]
It's outdated info that it does not support python 3.11 https://github.com/microsoft/onnxruntime/blob/1b07bbceaa234a37d0418d8e61f2d52dbd80af37/setup.py#L507. The support was added in v1.15.0 https://github.com/microsoft/onnxruntime/releases/tag/v1.15.0

2023-07-12 12:22 UTC, skupr-anaconda commented on recipe/meta.yaml
> -    - m2-patch # [win]
They are required if we apply patches.
```
    - patch    # [unix]
    - m2-patch # [win]
```
And check the anaconda-linter error about missing them

2023-07-12 12:26 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - git
```suggestion
    - git  # [not win]
```
**Prefect** already has git on `win64`. Also, this change will prevent crashing the `win64` agent on Prefect. See a corresponding error in the anaconda-linter log message

2023-07-12 12:28 UTC, skupr-anaconda commented
An error on osx-64:
```
dyld[1064]: Library not loaded: @rpath/libzstd.1.dylib

  Referenced from: <72742B14-65A8-3066-A0E4-314A22D5ECE8> /private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/cmake

  Reason: tried: '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libzstd.1.dylib' (no such file), '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)
```

2023-07-12 12:40 UTC, akabanovs commented
> An error on `osx-64`:
> 
> ```
> dyld[1064]: Library not loaded: @rpath/libzstd.1.dylib
> 
>   Referenced from: <72742B14-65A8-3066-A0E4-314A22D5ECE8> /private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/cmake
> 
>   Reason: tried: '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libzstd.1.dylib' (no such file), '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/private/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_ddtlf7r4qf/pkg_dirs/cmake-3.26.4-hbb7d193_0/bin/../lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)
> ```

Perhaps we need zstd package? It seems osx-64 was previously built succesfully? Perhaps something else provided zstd?

2023-07-13 21:24 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_7d_t1_qm7_/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-13 21:26 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:32: no_git_on_windows: git should not be used as a dependency on Windows.
ERROR: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_34yq26b0kq/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-13 21:27 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_43tqcxy_86/clone/recipe/meta.yaml:35: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_43tqcxy_86/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_43tqcxy_86/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_43tqcxy_86/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_43tqcxy_86/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_43tqcxy_86/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_43tqcxy_86/clone/recipe/meta.yaml:54: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-13 21:28 UTC, Arishamays1 commented on recipe/meta.yaml
> -    - m2-patch # [win]
Great! added this back. Thanks

2023-07-13 21:29 UTC, Arishamays1 commented on recipe/meta.yaml
> +  skip: True # [py>310 or ppc64le or s390x]
Thank you for letting me know! The setup.py and the 1.15.1 tag were a bit misleading.

2023-07-13 21:32 UTC, Arishamays1 commented on recipe/meta.yaml
> +    - numpy 1.21.5 # [py<310]
You're right! I believe this came from when python 3.11 was still unsupported for onnxruntime. Thanks!

2023-07-13 21:34 UTC, Arishamays1 commented on recipe/meta.yaml
> +    - numpy # [py>=310]
Added, however, will the selector be necessary if python 3.11 is now fully supported? I went ahead and removed them

2023-07-13 21:41 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_c0aq72mwu4/clone/recipe/meta.yaml:34: jinja_render_failure: The recipe could not be rendered by Jinja2
Errors were found

</details>

2023-07-13 21:42 UTC, Arishamays1 commented on recipe/meta.yaml
> +    - numpy 1.21.5   # [py<310]
Thanks will do

2023-07-13 21:43 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_75dd5jjp0b/clone/recipe/meta.yaml:47: jinja_render_failure: The recipe could not be rendered by Jinja2
Errors were found

</details>

2023-07-13 21:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:32: patch_must_be_in_build: patch must be in build when source/patches is set.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:37: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:38: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:39: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:40: build_tools_must_be_in_build: The build tool patch is not in the build section.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:40: build_tools_must_be_in_build: The build tool m2-patch is not in the build section.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:43: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_fb9ii9hope/clone/recipe/meta.yaml:53: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-13 21:50 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_3by91yop59/clone/recipe/meta.yaml:39: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3by91yop59/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3by91yop59/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3by91yop59/clone/recipe/meta.yaml:43: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_3by91yop59/clone/recipe/meta.yaml:44: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_3by91yop59/clone/recipe/meta.yaml:53: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-13 21:55 UTC, Arishamays1 commented on recipe/meta.yaml
> +    #   Workaround for https://github.com/microsoft/onnxruntime/issues/13225
done!

2023-07-13 21:56 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_18q2e_a9l2/clone/recipe/meta.yaml:38: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_18q2e_a9l2/clone/recipe/meta.yaml:39: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_18q2e_a9l2/clone/recipe/meta.yaml:40: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_18q2e_a9l2/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_18q2e_a9l2/clone/recipe/meta.yaml:43: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_18q2e_a9l2/clone/recipe/meta.yaml:52: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-14 20:59 UTC, ryanskeith requested changes
I think there are missing dependencies.  Also, I couldn't get the logs to download but there were some things on Prefect that had me worried that it wasn't finding libraries to build.  I think this library may also merit doing a full test to make sure it is functioning properly.

2023-07-14 20:59 UTC, ryanskeith commented on recipe/meta.yaml
>      - coloredlogs
I think you are missing some dependencies.  https://github.com/microsoft/onnxruntime/blob/main/requirements-training.txt.  There are several requirements files.  I think the runtime one is the _training IF I am reading things correctly.

2023-07-17 07:51 UTC, skupr-anaconda approved these changes
LGTM but `win` selector

2023-07-17 07:51 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - '**/api-ms-win-core-path-l1-1-0.dll'     # [win64]
```suggestion
  missing_dso_whitelist:     # [win]
    - '**/api-ms-win-core-path-l1-1-0.dll'     # [win]
```

2023-07-17 07:51 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - ninja     # [not win64]
```suggestion
    - git  # [not win]
    - ninja     # [not win]
```

2023-07-17 20:11 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_bdr6xn65le/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_bdr6xn65le/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_bdr6xn65le/clone/recipe/meta.yaml:43: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_bdr6xn65le/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_bdr6xn65le/clone/recipe/meta.yaml:46: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_bdr6xn65le/clone/recipe/meta.yaml:55: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>

2023-07-18 11:17 UTC, merged

2023-07-18 11:18 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_6cw3m6qwj7/clone/recipe/meta.yaml:41: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_6cw3m6qwj7/clone/recipe/meta.yaml:42: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_6cw3m6qwj7/clone/recipe/meta.yaml:43: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_6cw3m6qwj7/clone/recipe/meta.yaml:45: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_6cw3m6qwj7/clone/recipe/meta.yaml:46: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_6cw3m6qwj7/clone/recipe/meta.yaml:55: python_build_tool_in_run: The python build tool packaging is in run depends
ERROR: build.sh:53: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
Errors were found

</details>